# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Workflow CI

on:
  pull_request:
    branches: [ '*' ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  push:
    branches: [ 'master' ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-20.04' ]
        node_version: [ '18.20.4', '20.18.0' ]

    steps:
    - uses: actions/checkout@v4

    - name: Node JS Tests
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - run: npm install
    - run: npm test
